site_name: Modern system by LekhrajDinkar
site_description: Modern system by LekhrajDinkar
site_author: Lekhraj Dinkar
docs_dir: docs

# Navigation based on your Notes folder
nav:
  - Home:
    - Other site: index.md
    - About me: resume-builder/output/resume-from-tpl-1-profile-se3/resume-from-tpl-1-profile-se3_vlatest.md
  - Web : 03_web/index.md
  - Python:
      - kickoff: 02_funda/01_kickoff.md
      - lang_funda: 02_funda/00_py-funda.md
      - global-function: 02_funda/02_global-function.md
      - modules: 02_funda/03_module+DP.md
      - OOPS: 02_funda/04_programing-style.md
      - useful_function: 02_funda/05_useful_function.md
      - More üó®Ô∏è: chats.md

  - PySpark:
      - index: 01_pyspark/index.md
      - pandas: 01_pyspark/00_panda.md
      - setup_locally: 01_pyspark/01_setup_locally.md
      - architecture: 01_pyspark/02_architecture.md
      - ETL_01: 01_pyspark/03_ETL_1.md
      - ETL_02: 01_pyspark/03_ETL_2.md
      - file_format: 01_pyspark/04_file_format.md
      - pyspark_01: 01_pyspark/100_pyspark_01_start.md

  - GenAI:
      - index: 00_gen_ai/00_GenAI.md
      - AWS:
          - bedrock: 00_gen_ai/01_bedrock.md

theme:
  name: material
  features:
    - navigation.tracking          # Enables breadcrumbs
    - navigation.tabs              # Optional: if using tabs layout
    - navigation.top               # Scroll-to-top button
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer            # Enables next/previous at bottom
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: pink
  custom_dir: .
extra_css:
  - mkdocs.css

repo_url: https://github.com/lekhrajdinkar/02-etl-pyspark
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/